version: "2"
linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - gocritic
    - misspell
  exclusions:
    paths:
      - testdata
formatters:
  enable:
    - gofmt
