version: 2
project_name: civic-summary

builds:
  - main: .
    binary: civic-summary
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - arm64
      - amd64
    ldflags:
      - -s -w
      - -X github.com/AvogadroSG1/civic-summary/cmd.version={{.Version}}
      - -X github.com/AvogadroSG1/civic-summary/cmd.commit={{.ShortCommit}}
      - -X github.com/AvogadroSG1/civic-summary/cmd.date={{.Date}}

archives:
  - formats:
      - tar.gz

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
